export const ESPECIALIDADES = [
  "Alergología",
  "Anatomía patológica",
  "Anestesiología y reanimación",
  "Angiología y cirugía vascular",
  "Bioquímica clínica",
  "Cardiología",
  "Cirugía cardiovascular",
  "Cirugía general y del aparato digestivo",
  "Cirugía oral y maxilofacial",
  "Cirugía ortopédica y traumatología",
  "Cirugía pediátrica",
  "Cirugía plástica, estética y reparadora",
  "Cirugía torácica",
  "Dermatología médico-quirúrgica y venereología",
  "Dermatología",
  "Endocrinología y nutrición",
  "Farmacología clínica",
  "Geriatría",
  "Hematología y hemoterapia",
  "Hidrología médica",
  "Infectología",
  "Inmunología",
  "Medicina aeroespacial / medicina aeronáutica",
  "Medicina crítica / intensiva",
  "Medicina del deporte / medicina física y rehabilitación",
  "Medicina del trabajo",
  "Medicina familiar y comunitaria",
  "Medicina interna",
  "Medicina legal y forense",
  "Medicina nuclear",
  "Medicina paliativa",
  "Medicina preventiva y salud pública",
  "Medicina transfusional y hemoterapia",
  "Microbiología y parasitología",
  "Nefrología",
  "Neumología",
  "Neurocirugía",
  "Neurofisiología clínica",
  "Neurología",
  "Obstetricia y ginecología",
  "Oftalmología",
  "Oncología médica",
  "Otorrinolaringología",
  "Pediatría",
  "Psiquiatría",
  "Radiodiagnóstico",
  "Reumatología",
  "Urología",
] as const;

